[package]
name = "pprof"
version = "0.1.0"
edition = "2021"

[dependencies]
addr2line = "0.24"
object = "0.36"
memmap2 = "0.9"
flate2 = "1.0"
prost = "0.13"
prost-types = "0.13"
rustyline = "15"
regex = "1"

[build-dependencies]
prost-build = "0.13"
